version: "2.1"
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  # APP  ***************************************************************************************
  spring-boot-mongo-docker:
    image: mongo-service
    ports:
      - 25002:25002
    links:
      - mongo
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"

volumes:
  mongodb_data_container: